--
-- Author           : R. Collaris
-- Package          : companyModel
-- Diagram          : companyModel, is GDM: True
-- Date             : Feb 12, 2024, 11:33:35 AM
-- Version          : 1.0
-- Selected platform: h2
--
-- Generated by EaTool, used template: 01_01 no foreign key Create DDL for sats_Links.tmp
--

--
-- Drop statements
--
drop table if exists ROLE CASCADE CONSTRAINTS;
drop table if exists PERSON CASCADE CONSTRAINTS;
drop table if exists SAVINGSACCOUNT CASCADE CONSTRAINTS;
drop table if exists RESIDENTIALPERIOD CASCADE CONSTRAINTS;
drop table if exists CUSTOMER CASCADE CONSTRAINTS;
drop table if exists WORKHISTORY CASCADE CONSTRAINTS;
drop table if exists ADDRESS CASCADE CONSTRAINTS;
drop table if exists INLAY CASCADE CONSTRAINTS;
drop table if exists EMPLOYEE CASCADE CONSTRAINTS;
drop table if exists EMPLOYER CASCADE CONSTRAINTS;
drop table if exists link_Person_Role;
drop table if exists link_ResidentialPeriod;
drop table if exists link_WorkHistory;

--
-- Create statements
--

create table ROLE (
 pensionFundId                   integer             
,fromValidityDate                timestamp           
,id                              bigint              
,tillValidityDate                timestamp           
,CONSTRAINT ROLE_PK PRIMARY KEY(fromValidityDate, id)
);

create table PERSON (
 name                            character varying(50)
,gender                          character varying(5)
,birthday                        date                
,pensionFundId                   integer             
,fromValidityDate                timestamp           
,id                              bigint              
,tillValidityDate                timestamp           
,CONSTRAINT PERSON_PK PRIMARY KEY(fromValidityDate, id)
);

create table SAVINGSACCOUNT (
 amount                          real                
,accountNumber                   character varying(50)
,product                         character varying(2)
,measuredAt                      date                
,pensionFundId                   integer             
,fromValidityDate                timestamp           
,id                              bigint              
,tillValidityDate                timestamp           
,CONSTRAINT SAVINGSACCOUNT_PK PRIMARY KEY(product, measuredAt, fromValidityDate, id)
);

create table RESIDENTIALPERIOD (
 livesAtFrom                     date                
,livesAtTill                     date                
,pensionFundId                   integer             
,fromValidityDate                timestamp           
,id                              bigint              
,tillValidityDate                timestamp           
,CONSTRAINT RESIDENTIALPERIOD_PK PRIMARY KEY(fromValidityDate, id)
);

create table CUSTOMER (
 customerNumber                  character varying(50)
,customerMeasuredAt              date                
,totalSavingAmount               integer             
,pensionFundId                   integer             
,fromValidityDate                timestamp           
,id                              bigint              
,tillValidityDate                timestamp           
,CONSTRAINT CUSTOMER_PK PRIMARY KEY(fromValidityDate, id)
);

create table WORKHISTORY (
 tillDate                        date                
,fromDate                        date                
,income                          real                
,pensionFundId                   integer             
,fromValidityDate                timestamp           
,id                              bigint              
,tillValidityDate                timestamp           
,CONSTRAINT WORKHISTORY_PK PRIMARY KEY(fromValidityDate, id)
);

create table ADDRESS (
 street                          character varying(50)
,pensionFundId                   integer             
,fromValidityDate                timestamp           
,id                              bigint              
,tillValidityDate                timestamp           
,CONSTRAINT ADDRESS_PK PRIMARY KEY(fromValidityDate, id)
);

create table INLAY (
 inlayDate                       date                
,product                         character varying(2)
,inlayAmount                     real                
,pensionFundId                   integer             
,fromValidityDate                timestamp           
,id                              bigint              
,tillValidityDate                timestamp           
,CONSTRAINT INLAY_PK PRIMARY KEY(inlayDate, product, fromValidityDate, id)
);

create table EMPLOYEE (
 employeeId                      character varying(50)
,pensionFundId                   integer             
,fromValidityDate                timestamp           
,id                              bigint              
,tillValidityDate                timestamp           
,CONSTRAINT EMPLOYEE_PK PRIMARY KEY(fromValidityDate, id)
);

create table EMPLOYER (
 employerName                    character varying(50)
,pensionFundId                   integer             
,fromValidityDate                timestamp           
,id                              bigint              
,tillValidityDate                timestamp           
,CONSTRAINT EMPLOYER_PK PRIMARY KEY(id, fromValidityDate)
);

create table link_Person_Role (
 Person_id                      bigint              
,Role_id                        bigint              
);

create table link_ResidentialPeriod (
 ResidentialPeriod_id           bigint              
,Address_id                     bigint              
,Person_id                      bigint              
);

create table link_WorkHistory (
 WorkHistory_id                 bigint              
,Employee_id                    bigint              
,Employer_id                    bigint              
);

--
-- Einde template
--