--
-- Author           : R. Collaris
-- Package          : companyModel
-- Diagram          : companyModel, is GDM: True
-- Date             : May 27, 2024, 1:55:21 PM
-- Version          : 1.0
-- Selected platform: owl
--
-- Generated by EaTool, used template: 01_01 no foreign key Create DDL for sats_Links.ftl
--

--
-- Drop statements
--
drop table if exists ROLE CASCADE CONSTRAINTS;
drop table if exists PERSON CASCADE CONSTRAINTS;
drop table if exists SAVINGSACCOUNT CASCADE CONSTRAINTS;
drop table if exists RESIDENTIALPERIOD CASCADE CONSTRAINTS;
drop table if exists CUSTOMER CASCADE CONSTRAINTS;
drop table if exists WORKHISTORY CASCADE CONSTRAINTS;
drop table if exists ADDRESS CASCADE CONSTRAINTS;
drop table if exists INLAY CASCADE CONSTRAINTS;
drop table if exists EMPLOYEE CASCADE CONSTRAINTS;
drop table if exists EMPLOYER CASCADE CONSTRAINTS;
drop table if exists link_Person_Role;
drop table if exists link_ResidentialPeriod;
drop table if exists link_WorkHistory;

--
-- Create statements
--

create table ROLE (
 pensionFundId                   int                 
,fromValidityDate                dateTime            
,id                              long                
,tillValidityDate                dateTime            
,CONSTRAINT ROLE_PK PRIMARY KEY(fromValidityDate, id)
);

create table PERSON (
 name                            string(50)          
,gender                          string(5)           
,birthday                        date                
,pensionFundId                   int                 
,fromValidityDate                dateTime            
,id                              long                
,tillValidityDate                dateTime            
,CONSTRAINT PERSON_PK PRIMARY KEY(fromValidityDate, id)
);

create table SAVINGSACCOUNT (
 amount                          float               
,accountNumber                   string(50)          
,savingsAccountProduct           string(2)           
,measuredAt                      date                
,pensionFundId                   int                 
,fromValidityDate                dateTime            
,id                              long                
,tillValidityDate                dateTime            
,CONSTRAINT SAVINGSACCOUNT_PK PRIMARY KEY(savingsAccountProduct, measuredAt, fromValidityDate, id)
);

create table RESIDENTIALPERIOD (
 livesAtFrom                     date                
,livesAtTill                     date                
,pensionFundId                   int                 
,fromValidityDate                dateTime            
,id                              long                
,tillValidityDate                dateTime            
,CONSTRAINT RESIDENTIALPERIOD_PK PRIMARY KEY(fromValidityDate, id)
);

create table CUSTOMER (
 customerNumber                  string(50)          
,customerMeasuredAt              date                
,totalSavingAmount               int                 
,pensionFundId                   int                 
,fromValidityDate                dateTime            
,id                              long                
,tillValidityDate                dateTime            
,CONSTRAINT CUSTOMER_PK PRIMARY KEY(fromValidityDate, id)
);

create table WORKHISTORY (
 tillDate                        date                
,fromDate                        date                
,income                          float               
,pensionFundId                   int                 
,fromValidityDate                dateTime            
,id                              long                
,tillValidityDate                dateTime            
,CONSTRAINT WORKHISTORY_PK PRIMARY KEY(fromValidityDate, id)
);

create table ADDRESS (
 street                          string(50)          
,pensionFundId                   int                 
,fromValidityDate                dateTime            
,id                              long                
,tillValidityDate                dateTime            
,CONSTRAINT ADDRESS_PK PRIMARY KEY(fromValidityDate, id)
);

create table INLAY (
 inlayDate                       date                
,inlayProduct                    string(2)           
,inlayAmount                     float               
,pensionFundId                   int                 
,fromValidityDate                dateTime            
,id                              long                
,tillValidityDate                dateTime            
,CONSTRAINT INLAY_PK PRIMARY KEY(inlayDate, inlayProduct, fromValidityDate, id)
);

create table EMPLOYEE (
 employeeId                      string(50)          
,pensionFundId                   int                 
,fromValidityDate                dateTime            
,id                              long                
,tillValidityDate                dateTime            
,CONSTRAINT EMPLOYEE_PK PRIMARY KEY(fromValidityDate, id)
);

create table EMPLOYER (
 employerName                    string(50)          
,pensionFundId                   int                 
,fromValidityDate                dateTime            
,id                              long                
,tillValidityDate                dateTime            
,CONSTRAINT EMPLOYER_PK PRIMARY KEY(fromValidityDate, id)
);

create table link_Person_Role (
 Person_id                      long                
,Role_id                        long                
);

create table link_ResidentialPeriod (
 ResidentialPeriod_id           long                
,Address_id                     long                
,Person_id                      long                
);

create table link_WorkHistory (
 WorkHistory_id                 long                
,Employee_id                    long                
,Employer_id                    long                
);

--
-- Einde template
--